### ISSUE TITLE
test option and pretrained model for x2

### ISSUE THREAD

**Issue by cspk17** [Fried-Rice-Lab/EMT#1] opened 2023-05-29 02:14 UTC
I read your paper and thank you for sharing your ellexent work!!
The results for x2 senario are not included in the paper.
I want to test EMT for x2 using this repository.
But I find there is no the pretrained model and the option file (LSR_x2.yml).
Can you share the pretained model and option file for x2 senario??

**Comment by liozur** [comment] 2023-05-30 07:57
Thank you for your interest.

Due to hardware resources and budget constraints, we do not have training x2 EMT.

By the way, the code in this repository will be merged into our main repository in the future. At that time, we will provide more reproduction instructions.

**Closed as completed** 2023-06-09 01:35 UTC
